### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by srijeetHalder** [manojmj92/subtitle-downloader#39]
Traceback (most recent call last):
  File "C:\subtitle-downloader.py", line 19, in <module>
    import requests,time,re,zipfile
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "C:\subtitle-downloader.py", line 19, in <module>
    import requests,time,re,zipfile
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "C:\subtitle-downloader.py", line 19, in <module>
    import requests,time,re,zipfile
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "C:\subtitle-downloader.py", line 19, in <module>
    import requests,time,re,zipfile
ModuleNotFoundError: No module named 'requests'
GOTO was unexpected at this time.

Above error comes when I am using the script.

**Comment by marauderlabs** [comment]
same as #25. Already reported.

**Comment by manojmj92** [comment]
Have you installed the requests package?

**Comment by jay-ramani** [comment]
The latest version of the script is broken for packages and functionality as well.

Installed the requests, lxml, and BeautifulSoup packages. However, the script remains broken for SubDB search included! I manually searched on SubDB for many movies and found subtitles. Example, Moneyball released in 2011. The script however doesn't download from SubDB, I commented the SubScene code and put some debugs to find it's giving a 404 error.

When was this last tested to be working?

**Comment by ewwink** [comment]
there unnecessary module in this repos, like `requests` its only shorthand for urllib and we can replace with function `get()` like

```
def get(url):
     req = urllib2.Request(url)
     html = urllib2.urlopen(req).read()
     return html
```
second is module `bs4 (BeautifulSoup)` known as super slow html parser (http://blog.dispatched.ch/2010/08/16/beautifulsoup-vs-lxml-performance/) use instead lxml directly or powerful Regex so dont need to install module lxml.
another problem is search results is no longer with structure `a > span` tags but to capture the results we can use regex
`re.compile('href="(/subtitles/[^"]+)"').findall(html)`
I'm not an expert so let wait @manojmj92 to completely rewrite this project 😃
