### ISSUE TITLE
Cannot install missing modules

### ISSUE THREAD

**Issue by Tiwas** [manojmj92/subtitle-downloader#58]
Hi.
I was recommended this script, so went to try it. Installed python to my d: drive (windows 10), added python and python\scripts to my path, ran the script installed the requests module, tried again and it still failed. Went to install re, bs4 and zipfiles, but none of them will install. 

`pip install -vvv zipfiles
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Config variable 'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
Collecting zipfiles
  1 location(s) to search for versions of zipfiles:
  * https://pypi.python.org/simple/zipfiles/
  Getting page https://pypi.python.org/simple/zipfiles/
  Looking up "https://pypi.python.org/simple/zipfiles/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  https://pypi.python.org:443 "GET /simple/zipfiles/ HTTP/1.1" 404 37
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/zipfiles/: 404 Client Error: Not Found (zipfiles does not exist) for url: https://pypi.python.org/simple/zipfiles/ - skipping
  Could not find a version that satisfies the requirement zipfiles (from versions: )
Cleaning up...
No matching distribution found for zipfiles
Exception information:
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\python27\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "d:\python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "d:\python27\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "d:\python27\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "d:\python27\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for zipfiles`

Same thing happens for all of them. Is there a way to manually download or fix this?

Cheers!

**Comment by Tiwas** [comment]
Sorry. Got it working by installing the lxml module.
